name: Java CI Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Tomcat
        run: |
          sudo apt-get update
          sudo apt-get install -y tomcat9

      - name: Build with Ant
        run: ant -Djee.server.home=/usr/share/tomcat9